package config

const defaultConfigTemplate = `# promptd autogenerated config file

[defaults]
chat = "local:llama3"
fim = "local:qwen2.5-coder"
task = "local:llama3"
embed = "local:nomic-embed-text"

[providers.local]
scheme = "openai"
endpoint = "http://localhost:11434/v1"
key = "dummy"
`
